### PR TITLE
Updates to dependencies

### PR DESCRIPTION
**Pull request by IanWhitney**

### CODE REVIEW

**Review by eeklund — COMMENTED** [review]
I expected to see changes to or deletions of the `bin/lastpassify`, `bin/reek`. `bin/rubocop` binstubs.  Did you intend to leave those files unchanged?

I'm glad to see this change will also remove the active CVE with regard to the rake gem.

I am curious about the choice in ruby versions. Why select ruby 2.4.10 since it is EOL? Did you run into an incompatibility with newer versions?

**Comment by IanWhitney** [comment]
WIP, so not everything is done. 

As for Ruby version, I may have gone too far. The version we develop in can be more recent, but the version we support should probably be 2.3.1 or later. We still use this gem with some 2.3 projects and I don't want to break that support quite yet.

**Comment by IanWhitney** [comment]
@eeklund We think this is enough to cut a new version and then test to see if it resolves the warnings. What do you think?

**Review by eeklund — APPROVED** [review]
This looks good to me.  I don't see anything that requires changes and think it is ready for testing in a project and release.

Thanks for adding the brew file for the LastPass CLI and other improvements.  I hadn't seen the `.git/safe` path directory approach mentioned in the Thoughtbot blog.  

Is it common practice to exclude the bin/ directory from git? I don't recall seeing that in practice previously. Is that what effectively removes the Rake dependency warning?

**Comment by IanWhitney** [comment]
We _think_ the root cause was that we had binstubs in the repo. In looking at some other gems (rspec, standard, etc) we saw that they did not have a `bin` directory, so we followed that example.

To be honest, though, we're just trying this to see if it works.

**Pull request merged**
